services:
  - type: web
    name: smart-house-price-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: development
